### ISSUE TITLE
知乎日报页面调用多个接口数据的问题

### ISSUE THREAD

**Issue by ninety19** [laotan7237/EasyReader#10]
ZhiHuPresenterImpl这边调用了4个接口fetchDailyData();fetchHotList();fetchThemeList();fetchSectionList()
我看代码中是一个接口请求成功后再调用下一个接口，一直到最后一个接口调用成功。但是我学习Rxjava2时说它有个zip方法可以处理并行请求的问题，我想问下如果换成用zip方法该如何来写？

**Comment by laotan7237** [comment]
楼主没用过，你自己研究吧哈哈。
