### ISSUE TITLE
HttpUtil中在bugly日志抓到了一个错

### ISSUE THREAD

**Issue by tinglingmeng** [laotan7237/EasyReader#13]
Attempt to invoke interface method 'void com.xxx.xxx.xxx.xxx.LifeSubscription.bindSubscription(rx.Subscription)' on a null object reference
com.hm.youding.core.http.HttpUtils.invoke(HttpUtils.java:42);

         看了下是在这报的错
        Subscription subscription = observable.subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(callback);
        lifecycle.bindSubscription(subscription);
     因为是接手的代码,不懂这为么会有问题,麻烦作者有时间的话给看下呗

**Comment by laotan7237** [comment]
lifecycle加个空判断，有可能是因为你传进来的lifecycle被回收了，但是代码还跑这边。理论上你离开了，可以不用继续走业务逻辑了，所以空判断加上就OK了。
