### ISSUE TITLE
Error about "App.getAppComponent().mRetrofitDouBanUtils().fetchHotMovie();"

### ISSUE THREAD

**Issue by Bingoliallen** [laotan7237/EasyReader#3]
Error about "App.getAppComponent().mRetrofitDouBanUtils().fetchHotMovie();",please tell me how write a "RetrofitDouBanUtils" variate in App class

**Comment by laotan7237** [comment]
No, not at the moment "App.getAppComponent().mRetrofitDouBanUtils()",Test cases are out of date
